"""initial commit

Revision ID: 53603601b026
Revises: 
Create Date: 2022-01-14 00:28:18.621290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53603601b026"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("password", sa.String(), nullable=True),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email")
    )
    op.create_table("about",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("designation", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("phone", sa.String(), nullable=False),
    sa.Column("location", sa.String(), nullable=False),
    sa.Column("objective", sa.String(), nullable=True),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("certification",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("certificate_name", sa.String(), nullable=False),
    sa.Column("issue_by", sa.String(), nullable=False),
    sa.Column("expire_year", sa.String(), nullable=True),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("url", sa.String(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("connect",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("connect_name", sa.String(), nullable=False),
    sa.Column("image_url", sa.String(), nullable=False),
    sa.Column("url", sa.String(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("education",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("school_name", sa.String(), nullable=False),
    sa.Column("grade", sa.Integer(), nullable=False),
    sa.Column("out_of", sa.Integer(), nullable=False),
    sa.Column("degree", sa.String(), nullable=False),
    sa.Column("start_year", sa.Integer(), nullable=False),
    sa.Column("end_year", sa.Integer(), nullable=False),
    sa.Column("location", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("experience",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("designation", sa.String(), nullable=False),
    sa.Column("company_name", sa.String(), nullable=False),
    sa.Column("start_year", sa.Integer(), nullable=False),
    sa.Column("end_year", sa.Integer(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("location", sa.String(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("projects",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("project_name", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=False),
    sa.Column("url", sa.String(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("skills",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("skill_name", sa.String(), nullable=False),
    sa.Column("skill_type", sa.String(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skills")
    op.drop_table("projects")
    op.drop_table("experience")
    op.drop_table("education")
    op.drop_table("connect")
    op.drop_table("certification")
    op.drop_table("about")
    op.drop_table("user")
    # ### end Alembic commands ###
